### ISSUE TITLE
MNDWI SWED Model Error

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/CoastSeg#46]
# MNDWI SWED Model Error
- When I try to run the ` swed_water_mndwi` model I get the following error which leads me to suspect the RGB_to_MNDWI() outputs are incorrect. I used the data_sample.zip associated with the model at the [Zenodo release](https://zenodo.org/record/6824342#.YtnQQXbMKkd) . I've included the notebook and data to replicate this issue at the following branch on GitHub ``https://github.com/2320sharon/CoastSeg/tree/new_feature/MNDWI_models`` and included the same data in this issue.
- The notebook `MNDWI_model_error_notebook.ipynb` is on that branch which will let you replicate the error
- The notebook is also the zip file I have included.

## RGB_to_MNDWI()Function
- Take three arguments :
1. the path to the directory containing the RGB images
2. the path to the directory containing the NIR images
3. the path to the directory to store the MNDWI outputs in directory called 'MNDWI_outputs'
```
def RGB_to_MNDWI(self, RGB_dir_path:str, NIR_dir_path :str, output_path:str)->None:
        """Converts two directories of RGB and NIR imagery to MNDWI imagery in a directory named
         'MNDWI_outputs'.

        Args:
            RGB_dir_path (str): full path to directory containing RGB images
            NIR_dir_path (str): full path to directory containing NIR images
        
        Original Code from doodleverse_utils by Daniel Buscombe
        source: https://github.com/Doodleverse/doodleverse_utils
        """        
        paths=[RGB_dir_path,NIR_dir_path]
        files=[]
        for data_path in paths:
            if not os.path.exists(data_path):
                raise FileNotFoundError(f"{data_path} not found")
            f = sorted(glob(data_path+os.sep+'*.jpg'))
            if len(f)<1:
                f = sorted(glob(data_path+os.sep+'images'+os.sep+'*.jpg'))
            files.append(f)

        # creates matrix:  bands(RGB) x number of samples(NIR)
        # files=[['full_RGB_path.jpg','full_NIR_path.jpg'],
        # ['full_jpg_path.jpg','full_NIR_path.jpg']....]
        files = np.vstack(files).T

        # output_path: directory to store MNDWI outputs
        output_path += os.sep+ 'MNDWI_outputs'
        if not os.path.exists(output_path):
            os.mkdir(output_path)
        # Create subfolder to hold MNDWI ouputs in
        output_path=mk_new_dir('MNDWI_ouputs',output_path )
        

        for counter,f in enumerate(files):
            datadict={}
            # Read green band from RGB image and cast to float
            green_band = imread(f[0])[:,:,1].astype('float')
            # Read SWIR and cast to float
            swir = imread(f[1]).astype('float')
            # Transform 0 to np.NAN 
            green_band[green_band==0]=np.nan
            swir[swir==0]=np.nan
            # Mask out the NaNs
            green_band = np.ma.filled(green_band)
            swir = np.ma.filled(swir)
            
            # MNDWI imagery formula (Green – SWIR) / (Green + SWIR)
            mndwi = np.divide(swir - green_band, swir + green_band)
            # Convert the NaNs to -1
            mndwi[np.isnan(mndwi)]=-1
            # Rescale to be between 0 - 255
            mndwi = self.rescale_array(mndwi,0,255)
            # Save meta data for savez_compressed()
            datadict['arr_0'] = mndwi.astype(np.uint8)
            datadict['num_bands'] = 1
            datadict['files'] = [fi.split(os.sep)[-1] for fi in f]
            # Remove the file extension from the name
            ROOT_STRING = f[0].split(os.sep)[-1].split('.')[0]
            # save MNDWI as .npz file 
            segfile = output_path+os.sep+ROOT_STRING+'_noaug_nd_data_000000'+str(counter)+'.npz'
            np.savez_compressed(segfile, **datadict)
            del datadict, mndwi, green_band, swir
            
        return output_path

```

## Error Message
```
WARNING:tensorflow:Model was constructed with shape (None, 256, 256, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 256, 256, 1), dtype=tf.float32, name='input_1'), name='input_1', description="created by layer 'input_1'"), but it was called on an input with incompatible shape (1, 256, 256, 3).
  0%|                                                                                           | 0/16 [00:00<?, ?it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_7376\3195802537.py in <module>
     18 metadatadict=zoo_model.get_metadatadict(Ww,config_files, model_types)
     19 # # Compute the segmentation
---> 20 zoo_model.compute_segmentation(model_dict["sample_direc"], model_list, metadatadict)

C:\1_USGS\CoastSeg\repos\2_CoastSeg\CoastSeg_fork\Seg2Map\CoastSeg\zoo_model_module.py in compute_segmentation(self, sample_direc, model_list, metadatadict)
     51                 self.TARGET_SIZE,
     52                 TESTTIMEAUG,
---> 53                 WRITE_MODELMETADATA)
     54 
     55     def get_model(self, Ww: list):

~\anaconda3\envs\coastseg\lib\site-packages\doodleverse_utils\prediction_imports.py in do_seg(f, M, metadatadict, sample_direc, NCLASSES, N_DATA_BANDS, TARGET_SIZE, TESTTIMEAUG, WRITE_MODELMETADATA)
    169             # heatmap = make_gradcam_heatmap(tf.expand_dims(image, 0) , model)
    170 
--> 171             est_label = model.predict(tf.expand_dims(image, 0), batch_size=1).squeeze()
    172 
    173             if TESTTIMEAUG == True:

~\anaconda3\envs\coastseg\lib\site-packages\keras\utils\traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

~\anaconda3\envs\coastseg\lib\site-packages\keras\engine\training.py in tf__predict_function(iterator)
     13                 try:
     14                     do_return = True
---> 15                     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16                 except:
     17                     do_return = False

ValueError: in user code:

    File "C:\Users\Sharon\anaconda3\envs\coastseg\lib\site-packages\keras\engine\training.py", line 1845, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\Sharon\anaconda3\envs\coastseg\lib\site-packages\keras\engine\training.py", line 1834, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Sharon\anaconda3\envs\coastseg\lib\site-packages\keras\engine\training.py", line 1823, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\Sharon\anaconda3\envs\coastseg\lib\site-packages\keras\engine\training.py", line 1791, in predict_step
        return self(x, training=False)
    File "C:\Users\Sharon\anaconda3\envs\coastseg\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\Sharon\anaconda3\envs\coastseg\lib\site-packages\keras\engine\input_spec.py", line 249, in assert_input_compatibility
        f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Exception encountered when calling layer "model" (type Functional).
    
    Input 0 of layer "conv2d" is incompatible with the layer: expected axis -1 of input shape to have value 1, but received input with shape (1, 256, 256, 3)
    
    Call arguments received by layer "model" (type Functional):
      • inputs=tf.Tensor(shape=(1, 256, 256, 3), dtype=float64)
      • training=False
      • mask=None


```

## Notebook to Replicate Issue
- You will need to checkout to branch `https://github.com/2320sharon/CoastSeg/tree/new_feature/MNDWI_models` to run this notebook properly
- The notebook `MNDWI_model_error_notebook.ipynb` is on that branch which will let you replicate the error

## Data
I included the sample data I used to create the MNDWI outputs as well as the outputs I generated
[zenodo_sample_data.zip](https://github
[MNDWI_model_error_notebook.zip](https://github.com/dbuscombe-usgs/CoastSeg/files/9163374/MNDWI_model_error_notebook.zip)
.com/dbuscombe-usgs/CoastSeg/files/9162860/zenodo_sample_data.zip)
[MNDWI_ouputs_2022-07-21__07_hr_57_min14.zip](https://github.com/dbuscombe-usgs/CoastSeg/files/9162862/MNDWI_ouputs_2022-07-21__07_hr_57_min14.zip)

**Comment by dbuscombe-usgs** [comment]
I assigned myself to look at this.

**Comment by dbuscombe-usgs** [comment]
We now have new Zenodo models and a more streamlined way to implement them (https://github.com/Doodleverse/doodleverse_utils/issues/16)

NDWI and MNDWI file creation has been updated (https://github.com/Doodleverse/doodleverse_utils/issues/15)

so, this may no longer be an issue, but I will keep open until we have tested
